 # Pipeline configuration for processing input data
 # Types of input and output data:
 # - global, for the pipeline
 # - local, for the task (optional)

---

input type: float
output type: int
pipeline:
  - name: multiply
    input type: int
    output type: int
    args:
      - type: int
        value: 2
      
  - name: add
    input type: int
    output type: float
    args:
      - type: float
        value: 0.5
          
  - name: complex task
    input type: float
    output type: int
    kwargs:
      - name: strategy
        type: string
        value: interpolation
            
      